import streamlit as st
import base64
import numpy as np
import math
import csv
from PIL import Image
import pandas as pd
#from cryptography.fernet import Fernet



st.sidebar.subheader("***Navigation***")
menu=st.sidebar.selectbox("Select One to Proceed !",["Home","Encrypter","Decrypter","About App"])
if menu=="Home":
    # st.title("CryptiX")
    
    st.markdown("<h1 style='text-align: center; color: purple;font-size: 60px; '>CryptiX</h1>", unsafe_allow_html=True)
    st.markdown("<h2 style='text-align: center; color: purple;font-size: 30px; '>Your Secracy,Is Our Promise</h2>", unsafe_allow_html=True)
    image = Image.open("homepic1.jpg")
    st.image(image)
    st.markdown("***")
elif menu =="Encrypter":
    # st.write("pge 2")
    st.markdown("<h1 style='text-align: top-left; color: purple;font-size: 60px; '>Encrypter</h1>", unsafe_allow_html=True)
    key = Fernet.generate_key()
    with open('MYsecret.key', 'wb') as new_key_file:
        new_key_file.write(key)
        st.markdown("<h2 style='text-align:left; color: purple;font-size: 30px; '>Please Input A Secrete Message to Encrypt ! :-</h2>", unsafe_allow_html=True)
        #st.subheader("Please Input A Secrete Message to Encrypt ! :- ")
    msg=st.text_input("")
    msg = msg.encode()
    st.write("You Type :-",msg)
    
    f = Fernet(key)
# Pass your bytes type message into encrypt.
    ciphertext = f.encrypt(msg)
    
    st.subheader("Your Encryptrd Message Is:- ")
    st.write(ciphertext)
    image = Image.open("homepic1.jpg")
   
elif menu=="Decrypter":
    st.markdown("<h1 style='text-align:left; color: purple;font-size: 60px; '>Decrypter</h1>", unsafe_allow_html=True)
    # st.write("page 3")
    st.markdown("<h2 style='text-align:left; color: purple;font-size: 30px; '>Decrypted Message:- </h2>", unsafe_allow_html=True)
    #st.subheader("Decryption of Message")
    with open('Mysecret.key', 'rb') as my_private_key:
        key = my_private_key.read()
    f = Fernet(key)
    msg=st.text_input("")
    msg = msg.encode()
    ciphertext = f.encrypt(msg)
    
    cleartext = f.decrypt(ciphertext)
elif menu=="About App":

    st.markdown("<h1 style='text-align:left; color: purple;font-size: 35px; '>About App: </h1>", unsafe_allow_html=True)
    st.markdown("<h2 style='text-align:left; color: purple;font-size: 25px; '> This Application is using the AES128-bit Fernet cipher Algorithems.This is done with help of Python’s cryptography library. </h2>", unsafe_allow_html=True)
    st.markdown("***")
    st.markdown("<h1 style='text-align:left; color:	#000080;font-size: 35px; '>Working Principle: </h1>", unsafe_allow_html=True)
    image = Image.open("aboutus.jpg")
    st.image(image)
    st.markdown("***")
    st.markdown("<h2 style='text-align:left; color:#000080;font-size: 25px; '> A “key” or a “secret” in cryptography is just a chain of bytes generated by the cipher method (the encryption algorithm) that is used on one end to encrypt a message, and on the other end to decrypt a message.As long as you and another person have the same string of bytes, you’ll be able to encrypt a message into an indecipherable bunch of letters and numbers, and no one will be able to decode what you wrote without the key, or else at least some quantum computing power at their disposal. </h2>", unsafe_allow_html=True)
    st.markdown("***")
    
#st.markdown("<h1 style='text-align:left; color: purple;font-size: 35px; '>About App: </h1>", unsafe_allow_html=True)
   # st.markdown("<h2 style='text-align:left; color: purple;font-size: 25px; '>  </h2>", unsafe_allow_html=True)
    st.markdown("<h1 style='text-align:left; color:	#000080;font-size: 35px; '>What is Risk:</h1>", unsafe_allow_html=True)
    image = Image.open("needforsecurity.jpg")
    st.image(image)
    st.markdown("***")
    st.markdown("<h1 style='text-align:left; color: #2ECC71 ;font-size: 35px; '>Solution: </h1>", unsafe_allow_html=True)
    image = Image.open("encrypting.jpg")
    st.image(image)
    st.markdown("***")
    st.markdown("<h1 style='text-align:left; color:#E74C3C;font-size: 35px; '>Security: </h1>", unsafe_allow_html=True)
    image = Image.open("yousafe.jpg")
    st.image(image)
    st.markdown("<h2 style='text-align:left; color:#E74C3C;font-size: 25px; '> One-Step towards Security </h2>", unsafe_allow_html=True)
    st.write("page 4")
